# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control.proto',
  package='',
  serialized_pb='\n\rcontrol.proto\"\xe3\x02\n\x0e\x43ontrolRequest\x12)\n\x04type\x18\x01 \x02(\x0e\x32\x1b.ControlRequest.ControlType\x12\x30\n\rstart_request\x18\x02 \x01(\x0b\x32\x19.ControlStartShardRequest\x12.\n\x0cstop_request\x18\x03 \x01(\x0b\x32\x18.ControlStopShardRequest\x12\x32\n\x0estatus_request\x18\x04 \x01(\x0b\x32\x1a.ControlShardStatusRequest\x12\x34\n\x12shard_list_request\x18\x05 \x01(\x0b\x32\x18.ControlShardListRequest\"Z\n\x0b\x43ontrolType\x12\x08\n\x04NONE\x10\x00\x12\x0f\n\x0bSTART_SHARD\x10\x01\x12\x0e\n\nSTOP_SHARD\x10\x02\x12\x10\n\x0cSHARD_STATUS\x10\x03\x12\x0e\n\nSHARD_LIST\x10\x04\"\xcf\x02\n\x0c\x43ontrolReply\x12\'\n\x04type\x18\x01 \x02(\x0e\x32\x19.ControlReply.ControlType\x12,\n\x0bstart_reply\x18\x02 \x01(\x0b\x32\x17.ControlStartShardReply\x12*\n\nstop_reply\x18\x03 \x01(\x0b\x32\x16.ControlStopShardReply\x12.\n\x0cstatus_reply\x18\x04 \x01(\x0b\x32\x18.ControlShardStatusReply\x12\x30\n\x10shard_list_reply\x18\x05 \x01(\x0b\x32\x16.ControlShardListReply\"Z\n\x0b\x43ontrolType\x12\x08\n\x04NONE\x10\x00\x12\x0f\n\x0bSTART_SHARD\x10\x01\x12\x0e\n\nSTOP_SHARD\x10\x02\x12\x10\n\x0cSHARD_STATUS\x10\x03\x12\x0e\n\nSHARD_LIST\x10\x04\"-\n\x18\x43ontrolStartShardRequest\x12\x11\n\ttool_name\x18\x01 \x02(\t\"(\n\x16\x43ontrolStartShardReply\x12\x0e\n\x06status\x18\x01 \x02(\x05\":\n\x17\x43ontrolStopShardRequest\x12\x10\n\x08shard_id\x18\x01 \x02(\x05\x12\r\n\x05\x66lags\x18\x02 \x02(\x05\"\'\n\x15\x43ontrolStopShardReply\x12\x0e\n\x06status\x18\x01 \x02(\x05\"-\n\x19\x43ontrolShardStatusRequest\x12\x10\n\x08shard_id\x18\x01 \x02(\x05\")\n\x17\x43ontrolShardStatusReply\x12\x0e\n\x06status\x18\x01 \x02(\x05\"\x19\n\x17\x43ontrolShardListRequest\"\x94\x01\n\x15\x43ontrolShardListReply\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x34\n\nshard_data\x18\x02 \x03(\x0b\x32 .ControlShardListReply.ShardData\x1a\x35\n\tShardData\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06status\x18\x02 \x02(\t\x12\n\n\x02id\x18\x03 \x02(\x05')



_CONTROLREQUEST_CONTROLTYPE = _descriptor.EnumDescriptor(
  name='ControlType',
  full_name='ControlRequest.ControlType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_SHARD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_SHARD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHARD_STATUS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHARD_LIST', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=283,
  serialized_end=373,
)

_CONTROLREPLY_CONTROLTYPE = _descriptor.EnumDescriptor(
  name='ControlType',
  full_name='ControlReply.ControlType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START_SHARD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_SHARD', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHARD_STATUS', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHARD_LIST', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=283,
  serialized_end=373,
)


_CONTROLREQUEST = _descriptor.Descriptor(
  name='ControlRequest',
  full_name='ControlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ControlRequest.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_request', full_name='ControlRequest.start_request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop_request', full_name='ControlRequest.stop_request', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_request', full_name='ControlRequest.status_request', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shard_list_request', full_name='ControlRequest.shard_list_request', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLREQUEST_CONTROLTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=373,
)


_CONTROLREPLY = _descriptor.Descriptor(
  name='ControlReply',
  full_name='ControlReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ControlReply.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_reply', full_name='ControlReply.start_reply', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop_reply', full_name='ControlReply.stop_reply', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_reply', full_name='ControlReply.status_reply', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shard_list_reply', full_name='ControlReply.shard_list_reply', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLREPLY_CONTROLTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=376,
  serialized_end=711,
)


_CONTROLSTARTSHARDREQUEST = _descriptor.Descriptor(
  name='ControlStartShardRequest',
  full_name='ControlStartShardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tool_name', full_name='ControlStartShardRequest.tool_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=713,
  serialized_end=758,
)


_CONTROLSTARTSHARDREPLY = _descriptor.Descriptor(
  name='ControlStartShardReply',
  full_name='ControlStartShardReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ControlStartShardReply.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=760,
  serialized_end=800,
)


_CONTROLSTOPSHARDREQUEST = _descriptor.Descriptor(
  name='ControlStopShardRequest',
  full_name='ControlStopShardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shard_id', full_name='ControlStopShardRequest.shard_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='ControlStopShardRequest.flags', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=802,
  serialized_end=860,
)


_CONTROLSTOPSHARDREPLY = _descriptor.Descriptor(
  name='ControlStopShardReply',
  full_name='ControlStopShardReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ControlStopShardReply.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=862,
  serialized_end=901,
)


_CONTROLSHARDSTATUSREQUEST = _descriptor.Descriptor(
  name='ControlShardStatusRequest',
  full_name='ControlShardStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shard_id', full_name='ControlShardStatusRequest.shard_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=903,
  serialized_end=948,
)


_CONTROLSHARDSTATUSREPLY = _descriptor.Descriptor(
  name='ControlShardStatusReply',
  full_name='ControlShardStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ControlShardStatusReply.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=950,
  serialized_end=991,
)


_CONTROLSHARDLISTREQUEST = _descriptor.Descriptor(
  name='ControlShardListRequest',
  full_name='ControlShardListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=993,
  serialized_end=1018,
)


_CONTROLSHARDLISTREPLY_SHARDDATA = _descriptor.Descriptor(
  name='ShardData',
  full_name='ControlShardListReply.ShardData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ControlShardListReply.ShardData.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='ControlShardListReply.ShardData.status', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='ControlShardListReply.ShardData.id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=1116,
  serialized_end=1169,
)

_CONTROLSHARDLISTREPLY = _descriptor.Descriptor(
  name='ControlShardListReply',
  full_name='ControlShardListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ControlShardListReply.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shard_data', full_name='ControlShardListReply.shard_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CONTROLSHARDLISTREPLY_SHARDDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=1021,
  serialized_end=1169,
)

_CONTROLREQUEST.fields_by_name['type'].enum_type = _CONTROLREQUEST_CONTROLTYPE
_CONTROLREQUEST.fields_by_name['start_request'].message_type = _CONTROLSTARTSHARDREQUEST
_CONTROLREQUEST.fields_by_name['stop_request'].message_type = _CONTROLSTOPSHARDREQUEST
_CONTROLREQUEST.fields_by_name['status_request'].message_type = _CONTROLSHARDSTATUSREQUEST
_CONTROLREQUEST.fields_by_name['shard_list_request'].message_type = _CONTROLSHARDLISTREQUEST
_CONTROLREQUEST_CONTROLTYPE.containing_type = _CONTROLREQUEST;
_CONTROLREPLY.fields_by_name['type'].enum_type = _CONTROLREPLY_CONTROLTYPE
_CONTROLREPLY.fields_by_name['start_reply'].message_type = _CONTROLSTARTSHARDREPLY
_CONTROLREPLY.fields_by_name['stop_reply'].message_type = _CONTROLSTOPSHARDREPLY
_CONTROLREPLY.fields_by_name['status_reply'].message_type = _CONTROLSHARDSTATUSREPLY
_CONTROLREPLY.fields_by_name['shard_list_reply'].message_type = _CONTROLSHARDLISTREPLY
_CONTROLREPLY_CONTROLTYPE.containing_type = _CONTROLREPLY;
_CONTROLSHARDLISTREPLY_SHARDDATA.containing_type = _CONTROLSHARDLISTREPLY;
_CONTROLSHARDLISTREPLY.fields_by_name['shard_data'].message_type = _CONTROLSHARDLISTREPLY_SHARDDATA
DESCRIPTOR.message_types_by_name['ControlRequest'] = _CONTROLREQUEST
DESCRIPTOR.message_types_by_name['ControlReply'] = _CONTROLREPLY
DESCRIPTOR.message_types_by_name['ControlStartShardRequest'] = _CONTROLSTARTSHARDREQUEST
DESCRIPTOR.message_types_by_name['ControlStartShardReply'] = _CONTROLSTARTSHARDREPLY
DESCRIPTOR.message_types_by_name['ControlStopShardRequest'] = _CONTROLSTOPSHARDREQUEST
DESCRIPTOR.message_types_by_name['ControlStopShardReply'] = _CONTROLSTOPSHARDREPLY
DESCRIPTOR.message_types_by_name['ControlShardStatusRequest'] = _CONTROLSHARDSTATUSREQUEST
DESCRIPTOR.message_types_by_name['ControlShardStatusReply'] = _CONTROLSHARDSTATUSREPLY
DESCRIPTOR.message_types_by_name['ControlShardListRequest'] = _CONTROLSHARDLISTREQUEST
DESCRIPTOR.message_types_by_name['ControlShardListReply'] = _CONTROLSHARDLISTREPLY

class ControlRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLREQUEST

  # @@protoc_insertion_point(class_scope:ControlRequest)

class ControlReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLREPLY

  # @@protoc_insertion_point(class_scope:ControlReply)

class ControlStartShardRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLSTARTSHARDREQUEST

  # @@protoc_insertion_point(class_scope:ControlStartShardRequest)

class ControlStartShardReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLSTARTSHARDREPLY

  # @@protoc_insertion_point(class_scope:ControlStartShardReply)

class ControlStopShardRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLSTOPSHARDREQUEST

  # @@protoc_insertion_point(class_scope:ControlStopShardRequest)

class ControlStopShardReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLSTOPSHARDREPLY

  # @@protoc_insertion_point(class_scope:ControlStopShardReply)

class ControlShardStatusRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLSHARDSTATUSREQUEST

  # @@protoc_insertion_point(class_scope:ControlShardStatusRequest)

class ControlShardStatusReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLSHARDSTATUSREPLY

  # @@protoc_insertion_point(class_scope:ControlShardStatusReply)

class ControlShardListRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROLSHARDLISTREQUEST

  # @@protoc_insertion_point(class_scope:ControlShardListRequest)

class ControlShardListReply(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class ShardData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CONTROLSHARDLISTREPLY_SHARDDATA

    # @@protoc_insertion_point(class_scope:ControlShardListReply.ShardData)
  DESCRIPTOR = _CONTROLSHARDLISTREPLY

  # @@protoc_insertion_point(class_scope:ControlShardListReply)


# @@protoc_insertion_point(module_scope)
