# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yam.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import control_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yam.proto',
  package='',
  serialized_pb='\n\tyam.proto\x1a\rcontrol.proto\"R\n\rMessageHeader\x12\x1a\n\x04type\x18\x01 \x02(\x0e\x32\x0c.MessageType\x12\x11\n\tclient_id\x18\x02 \x01(\x0c\x12\x12\n\nsession_id\x18\x03 \x01(\x0c*Q\n\x0bMessageType\x12\x08\n\x04NONE\x10\x00\x12\x13\n\x0f\x43ONTROL_REQUEST\x10\x01\x12\x11\n\rCONTROL_REPLY\x10\x02\x12\x10\n\x0cTOOL_MESSAGE\x10\x03')

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROL_REQUEST', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTROL_REPLY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOOL_MESSAGE', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=112,
  serialized_end=193,
)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
NONE = 0
CONTROL_REQUEST = 1
CONTROL_REPLY = 2
TOOL_MESSAGE = 3



_MESSAGEHEADER = _descriptor.Descriptor(
  name='MessageHeader',
  full_name='MessageHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='MessageHeader.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='MessageHeader.client_id', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='MessageHeader.session_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=110,
)

_MESSAGEHEADER.fields_by_name['type'].enum_type = _MESSAGETYPE
DESCRIPTOR.message_types_by_name['MessageHeader'] = _MESSAGEHEADER

class MessageHeader(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MESSAGEHEADER

  # @@protoc_insertion_point(class_scope:MessageHeader)


# @@protoc_insertion_point(module_scope)
